import "./globals.css";
import { poppins, inter, liber } from '@/styles/fonts'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${inter.variable} ${liber.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
